name = "NuclearMasses"
uuid = "c9b28dd5-678b-49e4-aba3-c926706df1dc"
authors = ["Krzysztof Miernik <k.a.miernik@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
